// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyTracker.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneyTracker.Infrastructure.Migrations
{
    [DbContext(typeof(MoneyTrackerDbContext))]
    [Migration("20250627185707_Eliminar tabla income")]
    partial class Eliminartablaincome
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoneyTracker.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<string>("Color")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MoneyTracker.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#4CAF50",
                            Icon = "attach_money",
                            Name = "Salary",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#66BB6A",
                            Icon = "work_outline",
                            Name = "Freelance",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "#81C784",
                            Icon = "trending_up",
                            Name = "Investments",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Color = "#4CAF50",
                            Icon = "account_balance_wallet",
                            Name = "Initial Balance",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Color = "#F44336",
                            Icon = "account_balance_wallet",
                            Name = "Initial Balance",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Color = "#4CAF50",
                            Icon = "tune",
                            Name = "Balance Adjustment",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Color = "#F44336",
                            Icon = "tune",
                            Name = "Balance Adjustment",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Color = "#FF5722",
                            Icon = "restaurant",
                            Name = "Food",
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            Color = "#2196F3",
                            Icon = "commute",
                            Name = "Transport",
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            Color = "#3F51B5",
                            Icon = "home",
                            Name = "Rent",
                            Type = 2
                        },
                        new
                        {
                            Id = 13,
                            Color = "#FFC107",
                            Icon = "bolt",
                            Name = "Utilities",
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            Color = "#F44336",
                            Icon = "local_hospital",
                            Name = "Health",
                            Type = 2
                        },
                        new
                        {
                            Id = 20,
                            Color = "#9C27B0",
                            Icon = "sports_esports",
                            Name = "Entertainment",
                            Type = 2
                        },
                        new
                        {
                            Id = 21,
                            Color = "#E91E63",
                            Icon = "shopping_cart",
                            Name = "Shopping",
                            Type = 2
                        },
                        new
                        {
                            Id = 22,
                            Color = "#00BCD4",
                            Icon = "school",
                            Name = "Education",
                            Type = 2
                        },
                        new
                        {
                            Id = 23,
                            Color = "#FF9800",
                            Icon = "flight_takeoff",
                            Name = "Travel",
                            Type = 2
                        });
                });

            modelBuilder.Entity("MoneyTracker.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("MoneyTracker.Domain.Entities.Category", b =>
                {
                    b.HasOne("MoneyTracker.Domain.Entities.Category", "Parent")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MoneyTracker.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("MoneyTracker.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MoneyTracker.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MoneyTracker.Domain.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
