CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Accounts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Balance" numeric NOT NULL,
    "CreditLimit" numeric NOT NULL,
    "Notes" text,
    "Icon" character varying(50),
    "Color" character varying(10),
    "Type" text NOT NULL,
    CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id")
);

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(250) NOT NULL,
    "ParentId" integer,
    "Type" integer NOT NULL,
    "Icon" character varying(50),
    "Color" character varying(10),
    "IsSystem" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Categories_Categories_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Categories" ("Id") ON DELETE SET NULL
);

CREATE TABLE "Transaction" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Description" character varying(500),
    "AccountId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "PaymentMethod" integer,
    "Status" integer NOT NULL,
    "ScheduledDate" timestamp with time zone,
    "IsSystemGenerated" boolean NOT NULL,
    "TransferPairId" integer,
    "TransferType" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Transaction" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Transaction_Accounts_AccountId" FOREIGN KEY ("AccountId") REFERENCES "Accounts" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Transaction_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE SET NULL
);

CREATE TABLE "TransactionAttachments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TransactionId" integer NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "FileSize" integer NOT NULL,
    "ContentType" character varying(100) NOT NULL,
    "FileContent" bytea NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "UploadedDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TransactionAttachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TransactionAttachments_Transaction_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transaction" ("Id") ON DELETE CASCADE
);

INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (1, '#4CAF50', TIMESTAMPTZ '-infinity', NULL, 'AccountBalanceWallet', FALSE, TRUE, 'Initial Balance', NULL, 1, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (2, '#F44336', TIMESTAMPTZ '-infinity', NULL, 'AccountBalanceWallet', FALSE, TRUE, 'Initial Balance', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (3, '#4CAF50', TIMESTAMPTZ '-infinity', NULL, 'CurrencyExchange', FALSE, TRUE, 'Balance Adjustment', NULL, 1, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (4, '#F44336', TIMESTAMPTZ '-infinity', NULL, 'CurrencyExchange', FALSE, TRUE, 'Balance Adjustment', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (5, '#FF9800', TIMESTAMPTZ '-infinity', NULL, 'TrendingDown', FALSE, TRUE, 'Transfer Out', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (6, '#FF9800', TIMESTAMPTZ '-infinity', NULL, 'TrendingUp', FALSE, TRUE, 'Transfer In', NULL, 1, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (7, '#4CAF50', TIMESTAMPTZ '-infinity', NULL, 'CreditCard', FALSE, TRUE, 'Credit Card Payment', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (8, '#4CAF50', TIMESTAMPTZ '-infinity', NULL, 'Payments', FALSE, TRUE, 'Payment Received', NULL, 1, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (9, '#F44336', TIMESTAMPTZ '-infinity', NULL, 'CreditScore', FALSE, TRUE, 'Credit Advance', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (10, '#F44336', TIMESTAMPTZ '-infinity', NULL, 'Receipt', FALSE, TRUE, 'Advance Received', NULL, 1, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (11, '#4CAF50', TIMESTAMPTZ '-infinity', NULL, 'AttachMoney', FALSE, FALSE, 'Salary', NULL, 1, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (12, '#66BB6A', TIMESTAMPTZ '-infinity', NULL, 'WorkOutline', FALSE, FALSE, 'Freelance', NULL, 1, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (13, '#81C784', TIMESTAMPTZ '-infinity', NULL, 'TrendingUp', FALSE, FALSE, 'Investments', NULL, 1, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (14, '#FF5722', TIMESTAMPTZ '-infinity', NULL, 'Restaurant', FALSE, FALSE, 'Food', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (15, '#2196F3', TIMESTAMPTZ '-infinity', NULL, 'Commute', FALSE, FALSE, 'Transport', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (16, '#3F51B5', TIMESTAMPTZ '-infinity', NULL, 'Home', FALSE, FALSE, 'Rent/Mortgage', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (17, '#FFC107', TIMESTAMPTZ '-infinity', NULL, 'Bolt', FALSE, FALSE, 'Utilities', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (18, '#F44336', TIMESTAMPTZ '-infinity', NULL, 'LocalHospital', FALSE, FALSE, 'Health', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (19, '#9C27B0', TIMESTAMPTZ '-infinity', NULL, 'SportsEsports', FALSE, FALSE, 'Entertainment', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (20, '#E91E63', TIMESTAMPTZ '-infinity', NULL, 'ShoppingCart', FALSE, FALSE, 'Shopping', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (21, '#00BCD4', TIMESTAMPTZ '-infinity', NULL, 'School', FALSE, FALSE, 'Education', NULL, 2, TIMESTAMPTZ '-infinity');
INSERT INTO "Categories" ("Id", "Color", "CreatedAt", "DeletedAt", "Icon", "IsDeleted", "IsSystem", "Name", "ParentId", "Type", "UpdatedAt")
VALUES (22, '#FF9800', TIMESTAMPTZ '-infinity', NULL, 'FlightTakeoff', FALSE, FALSE, 'Travel', NULL, 2, TIMESTAMPTZ '-infinity');

CREATE INDEX "IX_Categories_ParentId" ON "Categories" ("ParentId");

CREATE INDEX "IX_Transaction_AccountId" ON "Transaction" ("AccountId");

CREATE INDEX "IX_Transaction_CategoryId" ON "Transaction" ("CategoryId");

CREATE INDEX "IX_TransactionAttachments_TransactionId" ON "TransactionAttachments" ("TransactionId");

SELECT setval(
    pg_get_serial_sequence('"Categories"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Categories") + 1,
        nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251112162726_initial data', '9.0.13');

ALTER TABLE "Transaction" DROP COLUMN "TransferType";

UPDATE "Categories" SET "Type" = 3
WHERE "Id" = 5;

UPDATE "Categories" SET "Color" = '#4CAF50', "Type" = 3
WHERE "Id" = 6;

UPDATE "Categories" SET "Color" = '#2196F3', "Type" = 3
WHERE "Id" = 7;

UPDATE "Categories" SET "Type" = 3
WHERE "Id" = 8;

UPDATE "Categories" SET "Color" = '#FF5722', "Type" = 3
WHERE "Id" = 9;

UPDATE "Categories" SET "Color" = '#4CAF50', "Type" = 3
WHERE "Id" = 10;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260116050112_FixPendingModelChanges', '9.0.13');

CREATE TABLE "Budgets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoryId" integer NOT NULL,
    "Year" integer NOT NULL,
    "Month" integer NOT NULL,
    "Amount" numeric(12,2) NOT NULL,
    "IncludeChildren" boolean NOT NULL,
    "RolloverEnabled" boolean NOT NULL,
    "RolloverMode" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_Budgets" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Budgets_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_Budgets_CategoryId_Year_Month" ON "Budgets" ("CategoryId", "Year", "Month") WHERE "IsDeleted" = false;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260209214256_budget', '9.0.13');

DROP INDEX "IX_Budgets_CategoryId_Year_Month";

DELETE FROM "Categories"
WHERE "Id" = 1;

DELETE FROM "Categories"
WHERE "Id" = 2;

DELETE FROM "Categories"
WHERE "Id" = 3;

DELETE FROM "Categories"
WHERE "Id" = 4;

DELETE FROM "Categories"
WHERE "Id" = 5;

DELETE FROM "Categories"
WHERE "Id" = 6;

DELETE FROM "Categories"
WHERE "Id" = 7;

DELETE FROM "Categories"
WHERE "Id" = 8;

DELETE FROM "Categories"
WHERE "Id" = 9;

DELETE FROM "Categories"
WHERE "Id" = 10;

DELETE FROM "Categories"
WHERE "Id" = 11;

DELETE FROM "Categories"
WHERE "Id" = 12;

DELETE FROM "Categories"
WHERE "Id" = 13;

DELETE FROM "Categories"
WHERE "Id" = 14;

DELETE FROM "Categories"
WHERE "Id" = 15;

DELETE FROM "Categories"
WHERE "Id" = 16;

DELETE FROM "Categories"
WHERE "Id" = 17;

DELETE FROM "Categories"
WHERE "Id" = 18;

DELETE FROM "Categories"
WHERE "Id" = 19;

DELETE FROM "Categories"
WHERE "Id" = 20;

DELETE FROM "Categories"
WHERE "Id" = 21;

DELETE FROM "Categories"
WHERE "Id" = 22;

ALTER TABLE "TransactionAttachments" ALTER COLUMN "ContentType" DROP NOT NULL;

ALTER TABLE "TransactionAttachments" ADD "TenantId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE "Transaction" ADD "TenantId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE "Categories" ADD "TenantId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE "Budgets" ADD "TenantId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

ALTER TABLE "Accounts" ADD "TenantId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';

CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "DisplayName" character varying(100),
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Tenants" (
    "TenantId" uuid NOT NULL,
    "Name" character varying(150) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "OwnerUserId" uuid NOT NULL,
    CONSTRAINT "PK_Tenants" PRIMARY KEY ("TenantId")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserAvatars" (
    "UserId" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "ContentType" character varying(20) NOT NULL,
    "Content" bytea NOT NULL,
    "SizeBytes" integer NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserAvatars" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_UserAvatars_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_TransactionAttachments_TenantId" ON "TransactionAttachments" ("TenantId");

CREATE INDEX "IX_Transaction_TenantId" ON "Transaction" ("TenantId");

CREATE INDEX "IX_Categories_TenantId" ON "Categories" ("TenantId");

CREATE INDEX "IX_Budgets_CategoryId" ON "Budgets" ("CategoryId");

CREATE INDEX "IX_Budgets_TenantId" ON "Budgets" ("TenantId");

CREATE UNIQUE INDEX "IX_Budgets_TenantId_CategoryId_Year_Month" ON "Budgets" ("TenantId", "CategoryId", "Year", "Month") WHERE "IsDeleted" = false;

CREATE INDEX "IX_Accounts_TenantId" ON "Accounts" ("TenantId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE UNIQUE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE UNIQUE INDEX "IX_Tenants_OwnerUserId" ON "Tenants" ("OwnerUserId");

CREATE INDEX "IX_UserAvatars_TenantId" ON "UserAvatars" ("TenantId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260305232909_MultiTenantIdentityAndProfile', '9.0.13');

ALTER TABLE "Categories" ADD "SystemCategoryCode" character varying(64);

CREATE UNIQUE INDEX "IX_Categories_TenantId_SystemCategoryCode" ON "Categories" ("TenantId", "SystemCategoryCode") WHERE "SystemCategoryCode" IS NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260305235728_SystemCategoryCodesPerTenant', '9.0.13');

COMMIT;

